<?php

namespace Database\Seeders;

use App\Models\Knife;
use Illuminate\Database\Seeder;

class KnifeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $knives = [
            [
                'knife_code' => 'A0678',
                'type' => 'مستطيل',
                'width' => 1.5,
                'length' => 14,
                'eyes_count' => 28,
                'gear' => 90,
                'dragile_drive' => 90,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'C0075',
                'type' => 'دائرة',
                'width' => 1.3,
                'length' => 1.3,
                'eyes_count' => 1,
                'gear' => 72,
                'dragile_drive' => 72,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'S0017',
                'type' => 'مربع',
                'width' => 2,
                'length' => 2,
                'eyes_count' => 4,
                'gear' => 80,
                'dragile_drive' => 80,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'O0023',
                'type' => 'بيضاوي',
                'width' => 1.6,
                'length' => 2.5,
                'eyes_count' => 6,
                'gear' => 83,
                'dragile_drive' => 83,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'SP001',
                'type' => 'شكل خاص',
                'width' => 2.1,
                'length' => 3.2,
                'eyes_count' => 9,
                'gear' => 96,
                'dragile_drive' => 96,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'W001',
                'type' => 'هالك',
                'width' => 1.7,
                'length' => 2.2,
                'eyes_count' => 12,
                'gear' => 100,
                'dragile_drive' => 100,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'E001',
                'type' => 'خارجي',
                'width' => 1.8,
                'length' => 2.3,
                'eyes_count' => 16,
                'gear' => 102,
                'dragile_drive' => 102,
                'rows_count' => 1,
                'notes' => 'خارجي 75',
            ],
            [
                'knife_code' => 'A0123',
                'type' => 'مستطيل',
                'width' => 2.5,
                'length' => 3.5,
                'eyes_count' => 20,
                'gear' => 104,
                'dragile_drive' => 104,
                'rows_count' => 2,
                'notes' => null,
            ],
            [
                'knife_code' => 'C0045',
                'type' => 'دائرة',
                'width' => 2.6,
                'length' => 2.6,
                'eyes_count' => 24,
                'gear' => 108,
                'dragile_drive' => 108,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'S0056',
                'type' => 'مربع',
                'width' => 3,
                'length' => 3,
                'eyes_count' => 25,
                'gear' => 111,
                'dragile_drive' => 111,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'O0078',
                'type' => 'بيضاوي',
                'width' => 3.2,
                'length' => 4.5,
                'eyes_count' => 30,
                'gear' => 114,
                'dragile_drive' => 114,
                'rows_count' => 2,
                'notes' => null,
            ],
            [
                'knife_code' => 'A0456',
                'type' => 'مستطيل',
                'width' => 3.3,
                'length' => 5,
                'eyes_count' => 40,
                'gear' => 90,
                'dragile_drive' => 90,
                'rows_count' => 2,
                'notes' => null,
            ],
            [
                'knife_code' => 'C0089',
                'type' => 'دائرة',
                'width' => 4,
                'length' => 4,
                'eyes_count' => 42,
                'gear' => 96,
                'dragile_drive' => 96,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'S0123',
                'type' => 'مربع',
                'width' => 4.5,
                'length' => 4.5,
                'eyes_count' => 48,
                'gear' => 100,
                'dragile_drive' => 100,
                'rows_count' => 2,
                'notes' => null,
            ],
            [
                'knife_code' => 'O0345',
                'type' => 'بيضاوي',
                'width' => 5,
                'length' => 6.4,
                'eyes_count' => 56,
                'gear' => 108,
                'dragile_drive' => 108,
                'rows_count' => 2,
                'notes' => null,
            ],
            [
                'knife_code' => 'A0789',
                'type' => 'مستطيل',
                'width' => 5.5,
                'length' => 7.5,
                'eyes_count' => 100,
                'gear' => 114,
                'dragile_drive' => 114,
                'rows_count' => 4,
                'notes' => null,
            ],
            [
                'knife_code' => 'C0123',
                'type' => 'دائرة',
                'width' => 6,
                'length' => 6,
                'eyes_count' => 12,
                'gear' => 72,
                'dragile_drive' => 72,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'S0456',
                'type' => 'مربع',
                'width' => 6.5,
                'length' => 6.5,
                'eyes_count' => 16,
                'gear' => 80,
                'dragile_drive' => 80,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'O0567',
                'type' => 'بيضاوي',
                'width' => 7,
                'length' => 8.5,
                'eyes_count' => 20,
                'gear' => 83,
                'dragile_drive' => 83,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'A0890',
                'type' => 'مستطيل',
                'width' => 8,
                'length' => 10,
                'eyes_count' => 24,
                'gear' => 90,
                'dragile_drive' => 90,
                'rows_count' => 2,
                'notes' => null,
            ],
            [
                'knife_code' => 'C0234',
                'type' => 'دائرة',
                'width' => 9,
                'length' => 9,
                'eyes_count' => 25,
                'gear' => 96,
                'dragile_drive' => 96,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'S0678',
                'type' => 'مربع',
                'width' => 10,
                'length' => 10,
                'eyes_count' => 28,
                'gear' => 100,
                'dragile_drive' => 100,
                'rows_count' => 2,
                'notes' => null,
            ],
            [
                'knife_code' => 'O0789',
                'type' => 'بيضاوي',
                'width' => 11,
                'length' => 13.9,
                'eyes_count' => 30,
                'gear' => 102,
                'dragile_drive' => 102,
                'rows_count' => 2,
                'notes' => null,
            ],
            [
                'knife_code' => 'A0901',
                'type' => 'مستطيل',
                'width' => 12,
                'length' => 14.9,
                'eyes_count' => 40,
                'gear' => 104,
                'dragile_drive' => 104,
                'rows_count' => 2,
                'notes' => null,
            ],
            [
                'knife_code' => 'C0345',
                'type' => 'دائرة',
                'width' => 13.9,
                'length' => 13.9,
                'eyes_count' => 42,
                'gear' => 108,
                'dragile_drive' => 108,
                'rows_count' => 2,
                'notes' => null,
            ],
            [
                'knife_code' => 'S0789',
                'type' => 'مربع',
                'width' => 14.9,
                'length' => 14.9,
                'eyes_count' => 48,
                'gear' => 111,
                'dragile_drive' => 111,
                'rows_count' => 2,
                'notes' => null,
            ],
            [
                'knife_code' => 'O0890',
                'type' => 'بيضاوي',
                'width' => 15.9,
                'length' => 16.8,
                'eyes_count' => 56,
                'gear' => 114,
                'dragile_drive' => 114,
                'rows_count' => 2,
                'notes' => null,
            ],
            [
                'knife_code' => 'A0902',
                'type' => 'مستطيل',
                'width' => 16,
                'length' => 16.9,
                'eyes_count' => 100,
                'gear' => 90,
                'dragile_drive' => 90,
                'rows_count' => 4,
                'notes' => null,
            ],
            [
                'knife_code' => 'C0789',
                'type' => 'دائرة',
                'width' => 17,
                'length' => 17,
                'eyes_count' => 12,
                'gear' => 72,
                'dragile_drive' => 72,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'S0890',
                'type' => 'مربع',
                'width' => 17.6,
                'length' => 17.6,
                'eyes_count' => 16,
                'gear' => 80,
                'dragile_drive' => 80,
                'rows_count' => 1,
                'notes' => null,
            ],
            [
                'knife_code' => 'O0901',
                'type' => 'بيضاوي',
                'width' => 23.5,
                'length' => 25,
                'eyes_count' => 20,
                'gear' => 83,
                'dragile_drive' => 83,
                'rows_count' => 1,
                'notes' => null,
            ],
        ];

        foreach ($knives as $knifeData) {
            // Calculate flap_size automatically if dragile_drive and length are provided
            $flapSize = null;
            if (!empty($knifeData['dragile_drive']) && !empty($knifeData['length'])) {
                $dragileDrive = (float)$knifeData['dragile_drive'];
                $length = (float)$knifeData['length'];
                
                if ($dragileDrive > 0 && $length > 0) {
                    // Formula: (((3.175 * dragileDrive / 10) / INT(3.175 * dragileDrive / (length + 0.2) / 10)) - length) * 10
                    $numerator = (3.175 * $dragileDrive / 10);
                    $denominator = floor(3.175 * $dragileDrive / ($length + 0.2) / 10);
                    
                    if ($denominator != 0) {
                        $flapSize = round((($numerator / $denominator) - $length) * 10, 3);
                    }
                }
            }

            Knife::updateOrCreate(
                ['knife_code' => $knifeData['knife_code']],
                array_merge($knifeData, ['flap_size' => $flapSize])
            );
        }
    }
}

